"""
Declarative Silver table specs -- one TableSpec per table, built from the real Bronze profile
(bronze_profile.md, generated by profile_bronze.py) rather than the data dictionary, which this
project has already found wrong three separate times before this pipeline even existed.

All 13 Bronze tables are specced here:
  - customers, branches, service_agents, marketing_campaigns: plain dimensions --
    string/numeric/date typing, country canonicalization.
  - products: dimension + currency conversion via the LATEST available FX rate (no natural "as of"
    date on a snapshot row).
  - transactions: fact + currency conversion via the EXACT-DATE FX rate, plus a fallback that
    fills the 57.34% of amount_usd that Bronze itself leaves null, using amount * that day's rate.
  - campaign_sends: fact + the literal "nan"-in-subject text bug fix.
  - call_center_interactions, call_transcripts, satisfaction_surveys, complaints, digital_events:
    facts, same typing/sentinel/country patterns as above; table-specific notes are next to each
    spec below (contact_reason/reason_category apparent duplication, origin_interaction_id drop,
    digital_events' size).

Every fact table drops the Hive partition columns (day, month, year) from its Silver output --
they're a Bronze/S3 storage artifact (DuckDB infers `year` as BIGINT, `month`/`day` stay VARCHAR
with leading zeros -- see profile_bronze.py's findings), not source data, and each table already
carries a real business timestamp/date column that supersedes them.

Naming convention: every table's `kind` ("dimension" or "fact") determines its silver.* prefix --
`silver.customers` is actually created as `silver.dim_customers`, `silver.transactions` as
`silver.fact_transactions`, and so on (TableSpec.silver_table_name() in silver.py does the
prefixing). `name` here stays UNPREFIXED throughout this file and matches the unprefixed
bronze.<name> source table and the --tables CLI filter -- only the actual CREATE TABLE target gets
prefixed. customers, branches, products, service_agents, marketing_campaigns (and the FX table,
dim_fx_rates) are dimensions; transactions, campaign_sends, call_center_interactions,
call_transcripts, satisfaction_surveys, complaints, digital_events are facts.
"""
from __future__ import annotations

from typing import List

if __package__:
    from .silver import ColumnSpec, TableSpec
    from .transforms import strip_templated_nan
else:  # direct run_silver.py execution
    from silver import ColumnSpec, TableSpec
    from transforms import strip_templated_nan

# --------------------------------------------------------------------------------------
# customers
# --------------------------------------------------------------------------------------
customers_spec = TableSpec(
    name="customers",
    kind="dimension",
    primary_key=["customer_id"],
    columns=[
        ColumnSpec("customer_id"),
        ColumnSpec("document_number"),
        ColumnSpec("document_type"),
        ColumnSpec("first_name"),
        ColumnSpec("last_name"),
        ColumnSpec("date_of_birth", transform="date"),
        ColumnSpec("gender"),
        ColumnSpec("email"),
        ColumnSpec("mobile_phone"),
        ColumnSpec("landline_phone"),
        ColumnSpec("address"),
        ColumnSpec("city"),
        ColumnSpec("state"),
        ColumnSpec("country", transform="country"),
        # Stays VARCHAR on purpose: the profile showed only 72.06% numeric-parseable (Latin
        # American postal formats mix alphanumeric and numeric), so casting to a numeric type
        # would silently NULL out a large share of real, valid postal codes.
        ColumnSpec("postal_code"),
        ColumnSpec("detected_accent"),
        ColumnSpec("segment"),
        ColumnSpec("credit_score", transform="double"),
        ColumnSpec("estimated_monthly_income", transform="double"),
        ColumnSpec("occupation"),
        ColumnSpec("marital_status"),
        ColumnSpec("education_level"),
        ColumnSpec("registration_date", transform="timestamp"),
        ColumnSpec("registration_branch_id"),
        ColumnSpec("customer_status"),
        # Profile showed a 2027 value here against a dataset that otherwise runs through
        # 2026-06-17 -- kept as-is (not clamped/dropped) since that's a data-quality judgment
        # call, not a typing decision; flag it downstream with e.g.
        # `SELECT * FROM silver.customers WHERE last_updated > current_timestamp` before trusting
        # any report built on customer recency.
        ColumnSpec("last_updated", transform="timestamp"),
        ColumnSpec("accepts_marketing", transform="boolean"),
    ],
)

# --------------------------------------------------------------------------------------
# branches
# --------------------------------------------------------------------------------------
branches_spec = TableSpec(
    name="branches",
    kind="dimension",
    primary_key=["branch_id"],
    columns=[
        ColumnSpec("branch_id"),
        ColumnSpec("branch_code"),
        ColumnSpec("branch_name"),
        ColumnSpec("branch_type"),
        ColumnSpec("address"),
        ColumnSpec("city"),
        ColumnSpec("state"),
        ColumnSpec("country", transform="country"),
        ColumnSpec("postal_code"),
        ColumnSpec("geographic_zone"),
        ColumnSpec("phone"),
        ColumnSpec("email"),
        ColumnSpec("opening_time", transform="time"),
        ColumnSpec("closing_time", transform="time"),
        ColumnSpec("has_atms", transform="boolean"),
        ColumnSpec("atm_count", transform="integer"),
        ColumnSpec("has_teller_windows", transform="boolean"),
        ColumnSpec("teller_window_count", transform="integer"),
        ColumnSpec("latitude", transform="double"),
        ColumnSpec("longitude", transform="double"),
        ColumnSpec("branch_opening_date", transform="date"),
        ColumnSpec("branch_status"),
    ],
)

# --------------------------------------------------------------------------------------
# products -- currency conversion via the LATEST available rate (a product snapshot row has no
# natural "as of" date to join an exact-date rate against, unlike a transaction).
# --------------------------------------------------------------------------------------
products_spec = TableSpec(
    name="products",
    kind="dimension",
    source_alias="p",
    extra_joins=[
        # Must run AFTER build_fx_rates_table() has created this view -- see run_silver.py.
        "LEFT JOIN silver.v_fx_latest_to_usd fx ON fx.source_currency = trim(p.currency)",
    ],
    primary_key=["product_id"],
    dedup_order_by="p._ingested_at DESC",
    columns=[
        ColumnSpec("p.product_id"),
        ColumnSpec("p.customer_id"),
        ColumnSpec("p.product_type"),
        ColumnSpec("p.product_number"),
        ColumnSpec("p.currency"),
        ColumnSpec("p.current_balance", transform="double"),
        ColumnSpec(
            source="p.current_balance", target="current_balance_usd",
            expr="TRY_CAST(p.current_balance AS DOUBLE) * fx.rate_to_usd",
        ),
        ColumnSpec("p.credit_limit", transform="double"),
        ColumnSpec(
            source="p.credit_limit", target="credit_limit_usd",
            expr="TRY_CAST(p.credit_limit AS DOUBLE) * fx.rate_to_usd",
        ),
        ColumnSpec("p.interest_rate", transform="double"),
        ColumnSpec("p.opening_date", transform="date"),
        ColumnSpec("p.expiration_date", transform="date"),
        ColumnSpec("p.opening_branch_id"),
        ColumnSpec("p.product_status"),
        ColumnSpec("p.opening_channel"),
        ColumnSpec("p.has_linked_app", transform="boolean"),
        ColumnSpec("p.days_past_due", transform="double"),
        ColumnSpec("p.last_transaction_date", transform="timestamp"),
        ColumnSpec("p.last_updated", transform="timestamp"),
    ],
)

# --------------------------------------------------------------------------------------
# transactions -- currency conversion via the EXACT-DATE rate (a transaction has a real date to
# join against), with a fallback that fills the gap Bronze itself leaves: amount_usd is null for
# 57.34% of rows (confirmed in the Bronze profile), computed here as amount * that day's rate
# whenever the source amount_usd is missing. amount_usd_is_estimated flags which rows are
# Silver-derived vs. genuinely sourced, so downstream analysis can decide whether to trust,
# exclude, or separately caveat the estimated ones.
# --------------------------------------------------------------------------------------
transactions_spec = TableSpec(
    name="transactions",
    kind="fact",
    source_alias="t",
    extra_joins=[
        "LEFT JOIN silver.dim_fx_rates fx "
        "ON fx.source_currency = trim(t.currency) "
        "AND fx.target_currency = 'USD' "
        "AND fx.rate_date = TRY_CAST(t.transaction_date AS DATE)",
    ],
    primary_key=["transaction_id"],
    dedup_order_by="t._ingested_at DESC",
    columns=[
        ColumnSpec("t.transaction_id"),
        ColumnSpec("t.transaction_date", transform="timestamp"),
        ColumnSpec("t.process_date", transform="date"),
        ColumnSpec("t.product_id"),
        ColumnSpec("t.customer_id"),
        ColumnSpec("t.transaction_type"),
        ColumnSpec("t.transaction_category"),
        ColumnSpec("t.amount", transform="double"),
        ColumnSpec("t.currency"),
        ColumnSpec(
            source="t.amount_usd", target="amount_usd",
            expr=(
                "COALESCE(TRY_CAST(t.amount_usd AS DOUBLE), "
                "TRY_CAST(t.amount AS DOUBLE) * fx.exchange_rate)"
            ),
        ),
        ColumnSpec(
            source="t.amount_usd", target="amount_usd_is_estimated",
            expr=(
                "(TRY_CAST(t.amount_usd AS DOUBLE) IS NULL "
                "AND TRY_CAST(t.amount AS DOUBLE) * fx.exchange_rate IS NOT NULL)"
            ),
        ),
        ColumnSpec("t.channel"),
        ColumnSpec("t.branch_id"),
        ColumnSpec("t.merchant_name"),
        ColumnSpec("t.merchant_category"),
        ColumnSpec("t.transaction_country", target="transaction_country", transform="country"),
        ColumnSpec("t.transaction_city"),
        ColumnSpec("t.transaction_status"),
        ColumnSpec("t.response_code"),
        ColumnSpec("t.is_fraud", transform="boolean"),
        ColumnSpec("t.fraud_score", transform="double"),
        ColumnSpec("t.latitude", transform="double"),
        ColumnSpec("t.longitude", transform="double"),
    ],
)

# --------------------------------------------------------------------------------------
# campaign_sends -- includes the strip_templated_nan() fix for the literal "nan" text found baked
# into 38,142 rows of `subject` (a NULL promoted-product name got string-formatted into a template
# upstream: '¡Oferta especial en nan!'). day/month/year (the Hive partition columns) are
# deliberately dropped here -- send_date is the real business timestamp; the partition columns are
# a Bronze/S3 storage artifact, not source data worth carrying into Silver.
# --------------------------------------------------------------------------------------
campaign_sends_spec = TableSpec(
    name="campaign_sends",
    kind="fact",
    primary_key=["send_id"],
    columns=[
        ColumnSpec("send_id"),
        ColumnSpec("send_date", transform="timestamp"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("campaign_id"),
        ColumnSpec("customer_id"),
        ColumnSpec("send_channel"),
        ColumnSpec("template_used"),
        ColumnSpec("subject", expr=strip_templated_nan("subject")),
        ColumnSpec("send_status"),
        ColumnSpec("was_delivered", transform="boolean"),
        ColumnSpec("was_opened", transform="boolean"),
        ColumnSpec("open_date", transform="timestamp"),
        ColumnSpec("was_clicked", transform="boolean"),
        ColumnSpec("click_date", transform="timestamp"),
        ColumnSpec("click_count", transform="integer"),
        ColumnSpec("had_conversion", transform="boolean"),
        ColumnSpec("conversion_date", transform="timestamp"),
        ColumnSpec("conversion_value", transform="double"),
        ColumnSpec("open_device"),
        ColumnSpec("open_country", transform="country"),
        ColumnSpec("failure_reason"),
        ColumnSpec("send_cost", transform="double"),
    ],
)

# --------------------------------------------------------------------------------------
# service_agents -- plain dimension, same pattern as branches.
# --------------------------------------------------------------------------------------
service_agents_spec = TableSpec(
    name="service_agents",
    kind="dimension",
    primary_key=["agent_id"],
    columns=[
        ColumnSpec("agent_id"),
        ColumnSpec("employee_code"),
        ColumnSpec("first_name"),
        ColumnSpec("last_name"),
        ColumnSpec("email"),
        ColumnSpec("phone"),
        ColumnSpec("native_accent"),
        ColumnSpec("country_of_origin", transform="country"),
        ColumnSpec("assigned_branch_id"),
        ColumnSpec("agent_type"),
        ColumnSpec("experience_level"),
        # Comma-separated list ('español, inglés') -- kept as a single string rather than split
        # into an array; no downstream table needs per-language filtering today, and DuckDB's
        # LIST/UNNEST can parse this later if that changes.
        ColumnSpec("languages"),
        ColumnSpec("specialty"),
        ColumnSpec("hire_date", transform="date"),
        ColumnSpec("avg_csat", transform="double"),
        ColumnSpec("total_monthly_interactions", transform="integer"),
        ColumnSpec("agent_status"),
        ColumnSpec("work_shift"),
    ],
)

# --------------------------------------------------------------------------------------
# marketing_campaigns -- plain dimension. Only 200 rows -- the campaign catalog, joined against by
# campaign_sends.campaign_id downstream.
# --------------------------------------------------------------------------------------
marketing_campaigns_spec = TableSpec(
    name="marketing_campaigns",
    kind="dimension",
    primary_key=["campaign_id"],
    columns=[
        ColumnSpec("campaign_id"),
        ColumnSpec("campaign_name"),
        ColumnSpec("description"),
        ColumnSpec("campaign_type"),
        ColumnSpec("campaign_objective"),
        ColumnSpec("promoted_product"),
        ColumnSpec("target_segment"),
        ColumnSpec("target_country", transform="country"),
        ColumnSpec("start_date", transform="date"),
        ColumnSpec("end_date", transform="date"),
        ColumnSpec("budget", transform="double"),
        ColumnSpec("campaign_status"),
        ColumnSpec("expected_conversion_rate", transform="double"),
    ],
)

# --------------------------------------------------------------------------------------
# call_center_interactions -- fact. NOTE: contact_reason and reason_category showed byte-for-byte
# identical value distributions in the Bronze profile (same 6 categories, same row counts down to
# the last digit -- 'Transaccional' (240,056) in both, etc.). That's strong evidence they're the
# same underlying value stored twice, but the profile only confirms matching AGGREGATE
# distributions, not a row-by-row identity check, so both are carried through unchanged here rather
# than silently dropping one on an assumption. Worth confirming with
# `SELECT count(*) FROM silver.fact_call_center_interactions WHERE contact_reason <>
# reason_category` (should return 0 if they really are duplicates) before treating either as safe
# to drop.
# --------------------------------------------------------------------------------------
call_center_interactions_spec = TableSpec(
    name="call_center_interactions",
    kind="fact",
    primary_key=["interaction_id"],
    columns=[
        ColumnSpec("interaction_id"),
        ColumnSpec("interaction_date", transform="timestamp"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("customer_id"),
        ColumnSpec("agent_id"),
        ColumnSpec("interaction_type"),
        ColumnSpec("channel"),
        ColumnSpec("contact_reason"),
        ColumnSpec("reason_category"),
        ColumnSpec("duration_seconds", transform="double"),
        ColumnSpec("wait_time_seconds", transform="double"),
        ColumnSpec("was_resolved", transform="boolean"),
        ColumnSpec("requires_followup", transform="boolean"),
        ColumnSpec("detected_sentiment"),
        ColumnSpec("sentiment_score", transform="double"),
        ColumnSpec("customer_detected_accent"),
        ColumnSpec("agent_used_accent"),
        ColumnSpec("was_escalated", transform="boolean"),
        # Comma-separated product-id list, same reasoning as service_agents.languages -- kept as a
        # single string rather than split/exploded.
        ColumnSpec("mentioned_products"),
        ColumnSpec("has_transcript", transform="boolean"),
        ColumnSpec("has_recording", transform="boolean"),
    ],
)

# --------------------------------------------------------------------------------------
# call_transcripts -- fact. full_text/customer_text/agent_text carry unrendered template
# placeholders ('{monto}', '{moneda}', '{limite}') in the raw data -- that's a Bronze/source-system
# fact this pipeline doesn't paper over; kept as-is rather than "fixed" here, since guessing at
# real values would fabricate data. mentioned_entities is a JSON-shaped string
# (e.g. '{"account_numbers": 0, "dates": 1, ...}') -- kept as VARCHAR rather than parsed, since no
# downstream table needs its fields split out yet; DuckDB's json_extract functions can read it
# directly from Silver later if that changes.
# --------------------------------------------------------------------------------------
call_transcripts_spec = TableSpec(
    name="call_transcripts",
    kind="fact",
    primary_key=["transcript_id"],
    columns=[
        ColumnSpec("transcript_id"),
        ColumnSpec("interaction_id"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("customer_id"),
        ColumnSpec("agent_id"),
        ColumnSpec("full_text"),
        ColumnSpec("customer_text"),
        ColumnSpec("agent_text"),
        ColumnSpec("detected_language"),
        ColumnSpec("detected_accent"),
        ColumnSpec("accent_confidence", transform="double"),
        ColumnSpec("detected_keywords"),
        ColumnSpec("mentioned_entities"),
        ColumnSpec("detected_intents"),
        ColumnSpec("main_topics"),
        ColumnSpec("transcription_model"),
        ColumnSpec("audio_quality"),
        ColumnSpec("duration_seconds", transform="double"),
    ],
)

# --------------------------------------------------------------------------------------
# satisfaction_surveys -- fact. main_score is a 1-7 integer scale spanning CSAT/NPS/CES survey
# types (not a single fixed scale across all rows -- survey_type tells you which); kept as a plain
# integer rather than normalized here, since collapsing three different scales into one comparable
# number is an analysis decision, not a typing one.
# --------------------------------------------------------------------------------------
satisfaction_surveys_spec = TableSpec(
    name="satisfaction_surveys",
    kind="fact",
    primary_key=["survey_id"],
    columns=[
        ColumnSpec("survey_id"),
        ColumnSpec("survey_date", transform="timestamp"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("interaction_id"),
        ColumnSpec("customer_id"),
        ColumnSpec("agent_id"),
        ColumnSpec("survey_type"),
        ColumnSpec("send_channel"),
        ColumnSpec("main_score", transform="integer"),
        ColumnSpec("nps_category"),
        ColumnSpec("question_1_text"),
        ColumnSpec("question_1_response", transform="double"),
        ColumnSpec("question_2_text"),
        ColumnSpec("question_2_response", transform="double"),
        ColumnSpec("question_3_text"),
        ColumnSpec("question_3_response", transform="double"),
        ColumnSpec("open_comments"),
        ColumnSpec("comment_sentiment"),
        ColumnSpec("response_time_hours", transform="double"),
        ColumnSpec("campaign_response_rate", transform="double"),
    ],
)

# --------------------------------------------------------------------------------------
# complaints -- fact. origin_interaction_id is DROPPED here: the Bronze profile found it 100% null
# / 0 distinct across all 67,095 rows -- a typed-but-always-null column carries zero information
# forward and this project has already agreed (see README) it's a real drop candidate, not a
# column to keep "just in case". claimed_amount/compensation_granted are typed to DOUBLE but NOT
# converted to USD here (unlike products/transactions) -- currency is 67.54% null on this table and
# there's no natural single "as of" date the way transactions has one; if USD comparability is
# needed later, the same extra_joins pattern transactions_spec uses (join dim_fx_rates on
# `creation_date`) can be added without changing anything else about this spec.
# --------------------------------------------------------------------------------------
complaints_spec = TableSpec(
    name="complaints",
    kind="fact",
    primary_key=["complaint_id"],
    columns=[
        ColumnSpec("complaint_id"),
        ColumnSpec("creation_date", transform="timestamp"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("customer_id"),
        ColumnSpec("case_type"),
        ColumnSpec("category"),
        ColumnSpec("subcategory"),
        ColumnSpec("reception_channel"),
        ColumnSpec("affected_product_id"),
        ColumnSpec("related_branch_id"),
        # origin_interaction_id intentionally dropped -- see spec docstring above.
        ColumnSpec("description"),
        ColumnSpec("claimed_amount", transform="double"),
        ColumnSpec("currency"),
        ColumnSpec("priority"),
        ColumnSpec("status"),
        ColumnSpec("assigned_agent_id"),
        ColumnSpec("assignment_date", transform="timestamp"),
        ColumnSpec("first_response_date", transform="timestamp"),
        ColumnSpec("resolution_date", transform="timestamp"),
        ColumnSpec("closing_date", transform="timestamp"),
        ColumnSpec("sla_breached", transform="boolean"),
        ColumnSpec("resolution_days", transform="double"),
        ColumnSpec("resolution"),
        ColumnSpec("compensation_granted", transform="double"),
        ColumnSpec("resolution_satisfaction", transform="double"),
        ColumnSpec("is_repeat_complainer", transform="boolean"),
    ],
)

# --------------------------------------------------------------------------------------
# digital_events -- fact, 15.6M rows -- the largest table in the dataset. Same typing/sentinel/
# country patterns as everything else; ip_country picks up the same 'México'/'Mexico' split
# COUNTRY_CANONICAL already fixes for transactions.transaction_country. No special-case logic
# needed here, but see the README for a real end-to-end timing once this runs against the full
# Bronze table (the smoke test in this repo only proves correctness on a tiny synthetic table, not
# that a local full rebuild stays fast at this row count).
# --------------------------------------------------------------------------------------
digital_events_spec = TableSpec(
    name="digital_events",
    kind="fact",
    primary_key=["event_id"],
    columns=[
        ColumnSpec("event_id"),
        ColumnSpec("event_date", transform="timestamp"),
        ColumnSpec("process_date", transform="date"),
        ColumnSpec("customer_id"),
        ColumnSpec("session_id"),
        ColumnSpec("event_type"),
        ColumnSpec("event_category"),
        ColumnSpec("channel"),
        ColumnSpec("platform"),
        ColumnSpec("browser"),
        ColumnSpec("app_version"),
        ColumnSpec("page_url"),
        ColumnSpec("page_title"),
        ColumnSpec("action"),
        ColumnSpec("element_id"),
        ColumnSpec("product_id"),
        ColumnSpec("event_value", transform="double"),
        ColumnSpec("duration_seconds", transform="double"),
        ColumnSpec("ip_address"),
        ColumnSpec("ip_country", transform="country"),
        ColumnSpec("ip_city"),
        ColumnSpec("is_mobile", transform="boolean"),
        ColumnSpec("referrer"),
        ColumnSpec("utm_source"),
        ColumnSpec("utm_medium"),
        ColumnSpec("utm_campaign"),
    ],
)

ALL_SPECS: List[TableSpec] = [
    customers_spec,
    branches_spec,
    products_spec,
    transactions_spec,
    campaign_sends_spec,
    service_agents_spec,
    marketing_campaigns_spec,
    call_center_interactions_spec,
    call_transcripts_spec,
    satisfaction_surveys_spec,
    complaints_spec,
    digital_events_spec,
]

# All 13 Bronze tables now have a TableSpec -- nothing left to implement. Kept as an empty list
# (rather than removed) so run_silver.py's PLANNED_NOT_YET_IMPLEMENTED handling doesn't need a
# code change if a 14th Bronze table shows up later.
PLANNED_NOT_YET_IMPLEMENTED: List[str] = []
