-- Fictitious demo identities and charges; slice_version: 809272f15d9f0eed
-- Contains no cases or sessions. Generated file: do not edit by hand.
INSERT INTO customers(customer_id,display_name) VALUES ('demo-ana','Ana (demo)') ON CONFLICT(customer_id) DO UPDATE SET display_name=CASE WHEN customers.display_name=excluded.display_name THEN customers.display_name ELSE NULL END;
INSERT INTO customers(customer_id,display_name) VALUES ('demo-bruno','Bruno (demo)') ON CONFLICT(customer_id) DO UPDATE SET display_name=CASE WHEN customers.display_name=excluded.display_name THEN customers.display_name ELSE NULL END;
INSERT INTO transactions(transaction_id,customer_id,occurred_at,source_occurred_at,merchant_name,amount,currency) VALUES ('demo-tx-001','demo-ana','2026-09-25T14:00:00+00:00',NULL,'Mercado Demo','125.50','BRL') ON CONFLICT(transaction_id) DO UPDATE SET customer_id=CASE WHEN transactions.customer_id=excluded.customer_id AND transactions.occurred_at IS excluded.occurred_at AND transactions.source_occurred_at IS excluded.source_occurred_at AND transactions.merchant_name=excluded.merchant_name AND transactions.amount=excluded.amount AND transactions.currency=excluded.currency THEN transactions.customer_id ELSE NULL END;
INSERT INTO transactions(transaction_id,customer_id,occurred_at,source_occurred_at,merchant_name,amount,currency) VALUES ('demo-tx-002','demo-ana','2026-09-26T15:00:00+00:00',NULL,'Loja Demo','89.90','BRL') ON CONFLICT(transaction_id) DO UPDATE SET customer_id=CASE WHEN transactions.customer_id=excluded.customer_id AND transactions.occurred_at IS excluded.occurred_at AND transactions.source_occurred_at IS excluded.source_occurred_at AND transactions.merchant_name=excluded.merchant_name AND transactions.amount=excluded.amount AND transactions.currency=excluded.currency THEN transactions.customer_id ELSE NULL END;
INSERT INTO transactions(transaction_id,customer_id,occurred_at,source_occurred_at,merchant_name,amount,currency) VALUES ('demo-tx-003','demo-bruno','2026-09-26T16:00:00+00:00',NULL,'Cafe Demo','32.00','BRL') ON CONFLICT(transaction_id) DO UPDATE SET customer_id=CASE WHEN transactions.customer_id=excluded.customer_id AND transactions.occurred_at IS excluded.occurred_at AND transactions.source_occurred_at IS excluded.source_occurred_at AND transactions.merchant_name=excluded.merchant_name AND transactions.amount=excluded.amount AND transactions.currency=excluded.currency THEN transactions.customer_id ELSE NULL END;
INSERT INTO transactions(transaction_id,customer_id,occurred_at,source_occurred_at,merchant_name,amount,currency) VALUES ('demo-tx-004','demo-ana','2026-09-27T10:30:00+00:00',NULL,'Farmacia Demo','47.30','BRL') ON CONFLICT(transaction_id) DO UPDATE SET customer_id=CASE WHEN transactions.customer_id=excluded.customer_id AND transactions.occurred_at IS excluded.occurred_at AND transactions.source_occurred_at IS excluded.source_occurred_at AND transactions.merchant_name=excluded.merchant_name AND transactions.amount=excluded.amount AND transactions.currency=excluded.currency THEN transactions.customer_id ELSE NULL END;
INSERT INTO transactions(transaction_id,customer_id,occurred_at,source_occurred_at,merchant_name,amount,currency) VALUES ('demo-tx-005','demo-ana','2026-09-28T19:45:00+00:00',NULL,'Posto Demo','210.00','BRL') ON CONFLICT(transaction_id) DO UPDATE SET customer_id=CASE WHEN transactions.customer_id=excluded.customer_id AND transactions.occurred_at IS excluded.occurred_at AND transactions.source_occurred_at IS excluded.source_occurred_at AND transactions.merchant_name=excluded.merchant_name AND transactions.amount=excluded.amount AND transactions.currency=excluded.currency THEN transactions.customer_id ELSE NULL END;
